aws_access_key        = "AWS_ACCESS_KEY"
aws_secret_key        = "AWS_SECRET_KEY"
azure_client_id       = "AZURE_CLIENT_ID"
azure_client_secret   = "AZURE_CLIENT_SECRET"
azure_subscription_id = "AZURE_SUBSCRIPTION_ID"
tenant_id             = "AZURE_TENANT_ID"